let modeloJson = [
    {
      id: 1,
      name: 'Coturno Rockstar',
      img: 'img/1.png',
      price: 200.00,
      sizes: ['couro', 'algodão', 'lona'],
      description: 'Cortuno Preto Estiloso',
    },
    {
      id: 2,
      name: 'Coturno Cowboy',
      img: 'img/2.png',
      price: 180.00,
      sizes: ['algodão', 'couro', 'lona'],
      description: 'Coturno Estilo Cowboy',
    },
    {
      id: 3,
      name: 'Coturno Classic',
      img: 'img/3.png',
      price: 150.00,
      sizes: ['lona', 'couro', 'algodão'],
      description: 'Coturno Preto Clássico',
    },
    {
      id: 4,
      name: 'Coturno Wine',
      img: 'img/4.png',
      price: 190.00,
      sizes: ['algodão', 'couro', 'lona'],
      description: 'Coturno Cor da Paixão',
    },
    {
      id: 5,
      name: 'Coturno AllWhite',
      img: 'img/5.png',
      price: 300.00,
      sizes: ['couro', 'algodão', 'lona'],
      description: 'Coturno Branco Minimalista',
    },
    {
      id: 6,
      name: 'Coturno RedDevil',
      img: 'img/6.png',
      price: 180.00,
      sizes: ['couro', 'lona', 'algodão'],
      description: 'Coturno Vermelho',
    },
  ];